site_name: My Notebook
theme:
  name: material
  palette:
    scheme: slate

nav:
  - Front Page: index.md
  - Writing Guide: markdown_guide.md
  - Git Guide: Git.md
  - Algorithm:
    - 基础数据结构: Basic_Algorithm.md
  - HTML:
    - Basic_HTML: HTML.md
    - Text_Format: HTML_textformat.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.caret
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - md_in_html
  - attr_list
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/extra.css